[tool.poetry]
name = "bareASGI-auth-server"
version = "0.1.0"
description = ""
authors = ["Rob Blackbourn <rblackbourn@ugsb-rbla01.bhdgsystematic.com>"]

[tool.poetry.dependencies]
python = "^3.7"
bareasgi = "^2.0"
bareasgi-jinja2 = "^2.0"
bareasgi-auth-common = "^0.1.0"
bareasgi-cors = "^2.0"
easydict = "^1.9"
PyYaml = "^5.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
