app:
  host: 127.0.0.1
  port: 20101
  http_server: uvicorn
  login_expiry: 1d
  path_prefix: /auth
  ssl:
    enabled: true
    keyfile: ~/.keys/server.key
    certfile: ~/.keys/server.crt

token_manager:
  cookie_name: bareasgi-auth
  secret: "not so secret"
  token_expiry: 1h
  domain: ${AUTH_DOMAIN}
  issuer: ${AUTH_ISSUER}
  path: /
  max_age: 1d
  token_renewal_path: /renew_token

sqlite:
  url: auth.db

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    bareasgi_auth_server:
      level: DEBUG
      handlers:
        - console
      propagate: false
  root:
    level: WARNING
    handlers:
      - console